# Generated by Django 5.1.4 on 2024-12-24 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('date_added', models.DateTimeField(verbose_name='date added')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['date_added'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=200, null=True)),
                ('description1', models.CharField(blank=True, default='', max_length=250)),
                ('description2', models.CharField(blank=True, default='', max_length=250)),
                ('description3', models.CharField(blank=True, default='', max_length=250)),
                ('description4', models.CharField(blank=True, default='', max_length=250)),
                ('description5', models.CharField(blank=True, default='', max_length=250)),
                ('description6', models.CharField(blank=True, default='', max_length=250)),
                ('description7', models.CharField(blank=True, default='', max_length=250)),
                ('brand', models.CharField(default='un-branded', max_length=100)),
                ('product_availability', models.CharField(choices=[('in stock', 'in stock'), ('out of stock', 'out of stock')], default='in stock', max_length=20)),
                ('image1', models.ImageField(default='default.jpg', upload_to='product1/img')),
                ('image2', models.ImageField(default='default.jpg', upload_to='product2/img')),
                ('image3', models.ImageField(default='default.jpg', upload_to='product3/img')),
                ('normal_price', models.PositiveBigIntegerField(null=True)),
                ('final_price', models.PositiveBigIntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='store.category')),
            ],
            options={
                'verbose_name_plural': 'products',
                'ordering': ['date_added'],
            },
        ),
    ]
