# Generated by Django 5.1.4 on 2024-12-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_image1_alter_product_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image3',
        ),
        migrations.AddField(
            model_name='product',
            name='image_one',
            field=models.ImageField(null=True, upload_to='product_img/one'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_three',
            field=models.ImageField(null=True, upload_to='product_img/three'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_two',
            field=models.ImageField(null=True, upload_to='product_img/two'),
        ),
    ]
