# Generated by Django 5.1.4 on 2024-12-30 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_product_image1_remove_product_image2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_one',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image_two',
            new_name='image2',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image_three',
            new_name='image3',
        ),
    ]
